"""RFM (Recency, Frequency, Monetary) Analysis Module for CustomerLens.

Transforms transaction-level customer purchase records into customer-level
behavioral features, calculates transparent quantile-based RFM scores,
assigns rule-based analytical customer segments, and provides validation utilities.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any, Dict, List, Optional, Union
import numpy as np
import pandas as pd

from src.data_loader import get_project_root

PROJECT_ROOT = get_project_root()
DEFAULT_INPUT_CSV = PROJECT_ROOT / "data" / "processed" / "customer_transactions.csv"
DEFAULT_OUTPUT_CSV = PROJECT_ROOT / "data" / "processed" / "rfm_customer_metrics.csv"

# Expected baseline validation constants
EXPECTED_CUSTOMERS = 4338
EXPECTED_ORDERS = 18532
EXPECTED_TOTAL_REVENUE = 8887208.89

REQUIRED_TRANSACTION_COLUMNS: List[str] = [
    "InvoiceNo",
    "InvoiceDate",
    "CustomerID",
    "Revenue",
    "Quantity",
    "UnitPrice",
    "Country",
]


# -----------------------------------------------------------------------------
# 1. Data Ingestion & Loading
# -----------------------------------------------------------------------------

def load_customer_transactions(
    filepath: Optional[Union[str, Path]] = None,
) -> pd.DataFrame:
    """Load and prepare validated customer transactions from CSV.

    Args:
        filepath: Optional path to customer transactions CSV. Defaults to
            data/processed/customer_transactions.csv.

    Returns:
        pd.DataFrame: Loaded transactions with parsed InvoiceDate.

    Raises:
        FileNotFoundError: If the specified CSV file does not exist.
        ValueError: If required columns are missing.
    """
    if filepath is None:
        filepath = DEFAULT_INPUT_CSV
    filepath = Path(filepath)

    if not filepath.is_file():
        raise FileNotFoundError(f"Customer transactions dataset not found at: {filepath}")

    df = pd.read_csv(filepath, dtype={"CustomerID": str, "InvoiceNo": str})

    missing_cols = [c for c in REQUIRED_TRANSACTION_COLUMNS if c not in df.columns]
    if missing_cols:
        raise ValueError(f"Transaction data is missing required columns: {missing_cols}")

    df["InvoiceDate"] = pd.to_datetime(df["InvoiceDate"])
    return df


# -----------------------------------------------------------------------------
# 2. Raw RFM Metric Computation
# -----------------------------------------------------------------------------

def calculate_rfm(
    df: pd.DataFrame,
    reference_date: Optional[Union[str, pd.Timestamp]] = None,
) -> pd.DataFrame:
    """Transform transaction-level data into customer-level RFM metrics.

    Definitions:
    - Recency: Integer number of elapsed days between customer's latest purchase
      and the dataset reference date (reference_date - max(InvoiceDate)).
    - Frequency: Number of distinct completed checkout orders (nunique InvoiceNo).
    - Monetary: Total completed revenue generated by the customer (sum Revenue).
    - Country: Primary billing country (mode country across orders).

    Args:
        df: Input transactions DataFrame.
        reference_date: Optional reference date. If None, dynamically derived as
            max(InvoiceDate) + pd.Timedelta(days=1).

    Returns:
        pd.DataFrame: Customer-level RFM DataFrame with one row per customer.

    Raises:
        ValueError: If input DataFrame violates required invariants (e.g. null CustomerID,
            empty dataset, negative quantities or prices).
    """
    if df.empty:
        raise ValueError("Cannot calculate RFM metrics on an empty DataFrame.")

    missing_cols = [c for c in REQUIRED_TRANSACTION_COLUMNS if c not in df.columns]
    if missing_cols:
        raise ValueError(f"Input DataFrame is missing required columns: {missing_cols}")

    if df["CustomerID"].isna().any():
        null_count = int(df["CustomerID"].isna().sum())
        raise ValueError(f"Found {null_count} rows with NULL CustomerID. All transactions must be attributed.")

    # Ensure valid transactional quantities and pricing
    if (df["Quantity"] <= 0).any():
        invalid_qty = int((df["Quantity"] <= 0).sum())
        raise ValueError(f"Found {invalid_qty} rows with Quantity <= 0.")

    if (df["UnitPrice"] <= 0).any():
        invalid_price = int((df["UnitPrice"] <= 0).sum())
        raise ValueError(f"Found {invalid_price} rows with UnitPrice <= 0.")

    # Ensure working copy has datetime InvoiceDate
    df_work = df.copy()
    df_work["InvoiceDate"] = pd.to_datetime(df_work["InvoiceDate"])

    # Derive reference date if not provided
    if reference_date is None:
        ref_date = df_work["InvoiceDate"].max() + pd.Timedelta(days=1)
    else:
        ref_date = pd.to_datetime(reference_date)

    # Vectorized group aggregations
    grouped = df_work.groupby("CustomerID")

    first_dates = grouped["InvoiceDate"].min()
    last_dates = grouped["InvoiceDate"].max()
    frequencies = grouped["InvoiceNo"].nunique()
    monetaries = grouped["Revenue"].sum().round(2)

    # Calculate integer recency days
    recencies = (ref_date - last_dates).dt.days

    # Mode country per customer to preserve 1-to-1 customer mapping
    countries = grouped["Country"].agg(lambda s: s.mode()[0] if not s.mode().empty else s.iloc[0])

    rfm = pd.DataFrame({
        "customerid": frequencies.index.astype(str),
        "recency": recencies.astype(int),
        "frequency": frequencies.astype(int),
        "monetary": monetaries.astype(float),
        "first_purchase_date": first_dates,
        "last_purchase_date": last_dates,
        "country": countries.values,
    }).reset_index(drop=True)

    # Sort deterministically by monetary spend descending
    rfm = rfm.sort_values(by=["monetary", "customerid"], ascending=[False, True]).reset_index(drop=True)
    return rfm


# -----------------------------------------------------------------------------
# 3. RFM Validation
# -----------------------------------------------------------------------------

def validate_rfm(
    rfm_df: pd.DataFrame,
    source_df: Optional[pd.DataFrame] = None,
) -> Dict[str, Any]:
    """Assert and verify that the RFM dataset satisfies all analytical invariants.

    Verifications:
    1. Exactly one row per customer (no duplicate CustomerID).
    2. CustomerID contains no null values.
    3. Recency is non-negative (>= 0).
    4. Frequency is positive integer (>= 1).
    5. Monetary is strictly positive (> 0).
    6. Customer count matches expected baseline or source dataset.
    7. Sum of monetary matches expected baseline or source dataset.
    8. Sum of frequency matches expected baseline or source dataset.
    9. Maximum last_purchase_date matches source dataset.

    Args:
        rfm_df: Customer-level RFM DataFrame to validate.
        source_df: Optional source transaction DataFrame for cross-comparison.

    Returns:
        Dict[str, Any]: Summary dictionary of validation results.

    Raises:
        ValueError: If any critical analytical invariant is violated.
    """
    if rfm_df.empty:
        raise ValueError("Validation failed: RFM DataFrame is empty.")

    total_customers = len(rfm_df)
    unique_customers = rfm_df["customerid"].nunique()

    # 1. Uniqueness check
    if total_customers != unique_customers:
        duplicates = total_customers - unique_customers
        raise ValueError(f"Validation failed: Found {duplicates} duplicate customer IDs.")

    # 2. Null check
    if rfm_df["customerid"].isna().any():
        null_count = int(rfm_df["customerid"].isna().sum())
        raise ValueError(f"Validation failed: Found {null_count} rows with null customer ID.")

    # 3. Recency check
    negative_recency = int((rfm_df["recency"] < 0).sum())
    if negative_recency > 0:
        raise ValueError(f"Validation failed: Found {negative_recency} customers with negative recency.")

    # 4. Frequency check
    invalid_freq = int((rfm_df["frequency"] < 1).sum())
    if invalid_freq > 0:
        raise ValueError(f"Validation failed: Found {invalid_freq} customers with frequency < 1.")

    # 5. Monetary check
    invalid_monetary = int((rfm_df["monetary"] <= 0).sum())
    if invalid_monetary > 0:
        raise ValueError(f"Validation failed: Found {invalid_monetary} customers with monetary <= 0.")

    total_frequency = int(rfm_df["frequency"].sum())
    total_monetary = round(float(rfm_df["monetary"].sum()), 2)

    # Cross-compare with source_df if provided
    if source_df is not None and not source_df.empty:
        expected_custs = source_df["CustomerID"].nunique()
        expected_orders = source_df["InvoiceNo"].nunique()
        expected_rev = round(float(source_df["Revenue"].sum()), 2)
        expected_max_date = pd.to_datetime(source_df["InvoiceDate"]).max()

        if total_customers != expected_custs:
            raise ValueError(f"Customer count mismatch: RFM={total_customers}, Source={expected_custs}")
        if total_frequency != expected_orders:
            raise ValueError(f"Order frequency mismatch: RFM={total_frequency}, Source={expected_orders}")
        if abs(total_monetary - expected_rev) > 0.05:
            raise ValueError(f"Monetary total mismatch: RFM={total_monetary}, Source={expected_rev}")

        rfm_max_date = pd.to_datetime(rfm_df["last_purchase_date"]).max()
        if rfm_max_date != expected_max_date:
            raise ValueError(f"Max date mismatch: RFM={rfm_max_date}, Source={expected_max_date}")

    validation_summary = {
        "status": "PASSED",
        "total_customers": total_customers,
        "unique_customers": unique_customers,
        "total_frequency": total_frequency,
        "total_monetary": total_monetary,
        "min_recency": int(rfm_df["recency"].min()),
        "max_recency": int(rfm_df["recency"].max()),
        "min_frequency": int(rfm_df["frequency"].min()),
        "max_frequency": int(rfm_df["frequency"].max()),
        "min_monetary": float(rfm_df["monetary"].min()),
        "max_monetary": float(rfm_df["monetary"].max()),
    }
    return validation_summary


# -----------------------------------------------------------------------------
# 4. Quantile Scoring & Tied-Boundary Handling
# -----------------------------------------------------------------------------

def _score_single_metric(
    series: pd.Series,
    num_scores: int = 5,
    ascending: bool = True,
    method: str = "quantile",
) -> pd.Series:
    """Assign discrete scores (1 to num_scores) to a metric series.

    Gracefully handles tied quantile boundaries and insufficient unique values.
    - If unique values <= 1, assigns constant score 1.
    - If quantile edges duplicate, drops duplicates and dynamically assigns
      available score levels.
    - Supports rank-based quantile scoring as deterministic fallback.

    Args:
        series: Numeric series to score.
        num_scores: Maximum number of score tiers (default 5).
        ascending: If True, higher metric values receive higher scores (e.g. Frequency, Monetary).
            If False, lower metric values receive higher scores (e.g. Recency).
        method: Scoring method ('quantile' with duplicate dropping or 'rank').

    Returns:
        pd.Series: Integer series of scores in valid range [1, num_scores].
    """
    if series.empty:
        return pd.Series(dtype=int)

    if series.nunique() <= 1:
        return pd.Series(1, index=series.index, dtype=int)

    if method == "rank":
        # Rank-based quantile binning: perfectly uniform distribution
        ranked = series.rank(method="first", ascending=ascending)
        labels = list(range(1, num_scores + 1))
        return pd.qcut(ranked, q=num_scores, labels=labels).astype(int)

    # Default quantile-based scoring with safe duplicate dropping
    try:
        _, edges = pd.qcut(series, q=num_scores, retbins=True, duplicates="drop")
        num_bins = len(edges) - 1
        if num_bins <= 1:
            return pd.Series(1, index=series.index, dtype=int)

        if ascending:
            labels = list(range(1, num_bins + 1))
        else:
            labels = list(range(num_bins, 0, -1))

        scores = pd.qcut(series, q=num_scores, labels=labels, duplicates="drop")
        return scores.astype(int)

    except Exception:
        # Fallback to deterministic rank-based scoring
        ranked = series.rank(method="first", ascending=ascending)
        labels = list(range(1, num_scores + 1))
        return pd.qcut(ranked, q=num_scores, labels=labels).astype(int)


def calculate_rfm_scores(
    rfm_df: pd.DataFrame,
    num_scores: int = 5,
    method: str = "quantile",
) -> pd.DataFrame:
    """Calculate R_score, F_score, M_score, and composite RFM_score.

    Scoring Directions:
    - Recency: Lower recency (more recent) -> Higher R_score (5 = most recent).
    - Frequency: Higher frequency (more orders) -> Higher F_score (5 = most frequent).
    - Monetary: Higher monetary (more spend) -> Higher M_score (5 = highest spend).
    - RFM_score: String concatenation of scores (e.g. '555', '111').

    Args:
        rfm_df: DataFrame with recency, frequency, and monetary columns.
        num_scores: Number of score tiers (default 5).
        method: Scoring strategy ('quantile' with safe duplicate drop, or 'rank').

    Returns:
        pd.DataFrame: Copy of rfm_df enriched with R_score, F_score, M_score, and RFM_score.
    """
    df_scored = rfm_df.copy()

    df_scored["R_score"] = _score_single_metric(
        df_scored["recency"],
        num_scores=num_scores,
        ascending=False,
        method=method,
    )
    df_scored["F_score"] = _score_single_metric(
        df_scored["frequency"],
        num_scores=num_scores,
        ascending=True,
        method=method,
    )
    df_scored["M_score"] = _score_single_metric(
        df_scored["monetary"],
        num_scores=num_scores,
        ascending=True,
        method=method,
    )

    df_scored["RFM_score"] = (
        df_scored["R_score"].astype(str)
        + df_scored["F_score"].astype(str)
        + df_scored["M_score"].astype(str)
    )
    return df_scored


# -----------------------------------------------------------------------------
# 5. Rule-Based Analytical Segment Assignment
# -----------------------------------------------------------------------------

def assign_rfm_segments(rfm_df: pd.DataFrame) -> pd.DataFrame:
    """Assign transparent, mutually exclusive analytical segments based on RFM scores.

    Segment Definitions (Mutually Exclusive Rules):
    1. Champions: Highly recent and highly frequent repeat purchasers (R >= 4 and F >= 4).
    2. Loyal Customers: Consistent repeat purchasers with good recency (R >= 3 and F >= 3).
    3. Potential Loyalists: Recent buyers with moderate order history (R >= 4 and F in (2, 3)).
    4. Recent Customers: First-time buyers with recent purchase activity (R >= 4 and F == 1).
    5. At Risk: High past order volume who have not purchased recently (R <= 2 and F >= 3).
    6. Need Attention: Above-average past buyers with deteriorating recency (R == 3 and F in (1, 2)).
    7. Hibernating: Low recency and low frequency purchasers (R == 2 and F <= 2).
    8. Lost: Lowest recency and lowest frequency buyers (R == 1 and F <= 2).

    Note: These segments are descriptive behavioral groupings and do not represent
    verified psychological states or guaranteed churn outcomes.

    Args:
        rfm_df: DataFrame containing R_score and F_score.

    Returns:
        pd.DataFrame: Enriched DataFrame with 'segment' column.
    """
    df_seg = rfm_df.copy()

    if "R_score" not in df_seg.columns or "F_score" not in df_seg.columns:
        raise ValueError("DataFrame must contain 'R_score' and 'F_score' to assign segments.")

    def _classify(row: pd.Series) -> str:
        r = row["R_score"]
        f = row["F_score"]

        # 1. Champions: highly recent, highly frequent
        if r >= 4 and f >= 4:
            return "Champions"
        # 2. Loyal Customers: consistent repeat buyers
        elif r >= 3 and f >= 3:
            return "Loyal Customers"
        # 3. Potential Loyalists: recent buyers with moderate orders
        elif r >= 4 and f in (2, 3):
            return "Potential Loyalists"
        # 4. Recent Customers: recent buyers with single order
        elif r >= 4 and f == 1:
            return "Recent Customers"
        # 5. At Risk: high past engagement, dormant recency
        elif r <= 2 and f >= 3:
            return "At Risk"
        # 6. Need Attention: moderate recency, low-to-moderate frequency
        elif r == 3 and f in (1, 2):
            return "Need Attention"
        # 7. Hibernating: low recency, low frequency
        elif r == 2 and f <= 2:
            return "Hibernating"
        # 8. Lost: lowest recency, low frequency
        elif r == 1 and f <= 2:
            return "Lost"
        else:
            return "Other"

    df_seg["segment"] = df_seg.apply(_classify, axis=1)
    return df_seg


# -----------------------------------------------------------------------------
# 6. Segment Profiling & Summary Statistics
# -----------------------------------------------------------------------------

def summarize_rfm(rfm_df: pd.DataFrame) -> pd.DataFrame:
    """Compute aggregate business metrics across RFM customer segments.

    Args:
        rfm_df: Segmented RFM DataFrame containing 'segment'.

    Returns:
        pd.DataFrame: Segment-level summary scorecard.
    """
    if "segment" not in rfm_df.columns:
        raise ValueError("RFM DataFrame must contain 'segment' column to summarize.")

    total_customers = len(rfm_df)
    total_rev = rfm_df["monetary"].sum()
    total_orders = rfm_df["frequency"].sum()

    summary = rfm_df.groupby("segment").agg(
        customer_count=("customerid", "count"),
        total_revenue=("monetary", "sum"),
        total_orders=("frequency", "sum"),
        mean_recency=("recency", "mean"),
        median_recency=("recency", "median"),
        mean_frequency=("frequency", "mean"),
        median_frequency=("frequency", "median"),
        mean_monetary=("monetary", "mean"),
        median_monetary=("monetary", "median"),
    ).reset_index()

    summary["pct_customers"] = (summary["customer_count"] * 100.0 / total_customers).round(2)
    summary["pct_revenue"] = (summary["total_revenue"] * 100.0 / total_rev).round(2)
    summary["aov"] = (summary["total_revenue"] / summary["total_orders"]).round(2)

    # Round currency and averages
    summary["total_revenue"] = summary["total_revenue"].round(2)
    summary["mean_recency"] = summary["mean_recency"].round(1)
    summary["mean_frequency"] = summary["mean_frequency"].round(2)
    summary["mean_monetary"] = summary["mean_monetary"].round(2)
    summary["median_monetary"] = summary["median_monetary"].round(2)

    # Sort descending by total revenue
    summary = summary.sort_values(by="total_revenue", ascending=False).reset_index(drop=True)
    return summary


# -----------------------------------------------------------------------------
# 7. Dataset Persistence
# -----------------------------------------------------------------------------

def save_rfm_dataset(
    rfm_df: pd.DataFrame,
    output_path: Optional[Union[str, Path]] = None,
) -> Path:
    """Save processed RFM customer metrics to CSV.

    Args:
        rfm_df: Processed RFM DataFrame.
        output_path: Target CSV file path. Defaults to
            data/processed/rfm_customer_metrics.csv.

    Returns:
        Path: Path to saved file.
    """
    if output_path is None:
        output_path = DEFAULT_OUTPUT_CSV
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    rfm_df.to_csv(output_path, index=False)
    return output_path


# -----------------------------------------------------------------------------
# 8. End-to-End Pipeline Execution
# -----------------------------------------------------------------------------

def run_rfm_pipeline(
    input_path: Optional[Union[str, Path]] = None,
    output_path: Optional[Union[str, Path]] = None,
) -> pd.DataFrame:
    """Execute the complete deterministic RFM analysis pipeline.

    Steps:
    1. Load customer transactions.
    2. Compute raw Recency, Frequency, and Monetary metrics.
    3. Validate all analytical invariants.
    4. Calculate quantile RFM scores.
    5. Assign analytical customer segments.
    6. Export results to CSV.

    Returns:
        pd.DataFrame: Fully enriched and validated RFM dataset.
    """
    print("Executing CustomerLens Phase 8 RFM Pipeline...")
    tx_df = load_customer_transactions(input_path)
    print(f"  Loaded {len(tx_df):,} transaction rows.")

    rfm_df = calculate_rfm(tx_df)
    print(f"  Aggregated {len(rfm_df):,} customer accounts.")

    validation = validate_rfm(rfm_df, tx_df)
    print(f"  Validation status: {validation['status']}")

    scored_df = calculate_rfm_scores(rfm_df)
    segmented_df = assign_rfm_segments(scored_df)

    saved_path = save_rfm_dataset(segmented_df, output_path)
    print(f"  Saved processed RFM dataset to: {saved_path}")

    return segmented_df


if __name__ == "__main__":
    run_rfm_pipeline()
