table Ref_MarketingOpportunities
	lineageTag: d1dfe1b5-aa4b-47ba-9e05-e872db3f47d2

	column cluster_id
		dataType: int64
		lineageTag: 25b3e073-1419-45c2-a0b3-8692d065f138
		sourceColumn: cluster_id

	column business_segment
		dataType: string
		lineageTag: c1f492f5-4f37-4311-8841-fbe3f885c8cf
		sourceColumn: business_segment
		sortByColumn: cluster_id

	column action_category
		dataType: string
		lineageTag: d8761d5b-8273-4d96-b7f6-89fe52421b5a
		sourceColumn: action_category

	column customer_count
		dataType: int64
		lineageTag: c9bbb0b8-0008-43ed-a8a8-58c0204dfd9b
		sourceColumn: customer_count

	column customer_percentage
		dataType: double
		lineageTag: e409ee08-42c6-4d01-9a99-0ff980b97f53
		sourceColumn: customer_percentage

	column revenue
		dataType: double
		formatString: £#,##0.00
		lineageTag: 1a7ea71e-546f-44d2-a604-cd24116dda74
		sourceColumn: revenue

	column revenue_percentage
		dataType: double
		lineageTag: d8eb73d6-a0b7-4854-935d-71f43b7070a6
		sourceColumn: revenue_percentage

	column primary_characteristic
		dataType: string
		lineageTag: 04c90c5b-12ed-4998-b452-7a25c2c2b317
		sourceColumn: primary_characteristic

	column business_opportunity
		dataType: string
		lineageTag: 3cc75477-6ddc-457f-855e-9769eb6fa6b6
		sourceColumn: business_opportunity

	column recommended_action
		dataType: string
		lineageTag: 8e23a029-fdd5-492e-aa63-947d51620d9f
		sourceColumn: recommended_action

	column measurement_metric
		dataType: string
		lineageTag: fe2b11a8-41a6-4514-9cae-9a8f7e4795a5
		sourceColumn: measurement_metric

	column caveat
		dataType: string
		lineageTag: f94b71a6-f5b0-4c54-90bc-9a301de18e63
		sourceColumn: caveat

	partition Ref_MarketingOpportunities = m
		mode: import
		source = let Source = Csv.Document(File.Contents("C:/Users/divya/OneDrive/Desktop/Customer_Lens/data/processed/marketing_opportunities.csv"),[Delimiter=",", Columns=12, Encoding=65001, QuoteStyle=QuoteStyle.Csv]), #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]), #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"cluster_id", Int64.Type}, {"business_segment", type text}, {"action_category", type text}, {"customer_count", Int64.Type}, {"customer_percentage", type number}, {"revenue", type number}, {"revenue_percentage", type number}, {"primary_characteristic", type text}, {"business_opportunity", type text}, {"recommended_action", type text}, {"measurement_metric", type text}, {"caveat", type text}}) in #"Changed Type"

